version: "3.8"
services:
  # INFRASTRUCTURE
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  # APP SERVICE
  member-service:
    container_name: member-service
    image: nantaaditya/member-app:0.0.1-SNAPSHOT
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - R2DBC_URL=r2dbc:postgresql://postgres:5432/local_db
      - SLOW_RESPONSE_THRESHOLD=500
    depends_on:
      - db
      - redis
      - kafka
    ports:
      - "8000:8000"
  core-service:
    container_name: core-service
    image: nantaaditya/core-app:0.0.1-SNAPSHOT
    environment:
      - R2DBC_URL=r2dbc:postgresql://postgres:5432/local_db
      - SLOW_RESPONSE_THRESHOLD=500
    depends_on:
      - db
      - member-service
      - kafka
    ports:
      - "8001:8001"

  # MONITORING
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - core-service
      - member-service
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - member-service
      - core-service
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - loki
      - core-service
      - member-service

volumes:
  local_pgdata:
  pgadmin-data:
