server:
  port: 8000
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  application:
    name: member-app
  r2dbc:
#    url: r2dbc:postgresql://host.docker.internal:5432/local_db
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/local_db}
    username: 'user'
    password: 'password'

# logging
logging:
  level:
    com.nantaaditya.framework.test: DEBUG
    com.nantaaditya.framework.redis: DEBUG
    com.nantaaditya.framework.helper: INFO
    com.nantaaditya.framework.kafka: DEBUG
  file:
    name: logs/member.log
#    io.r2dbc.postgresql.QUERY: DEBUG
#    io.r2dbc.postgresql.PARAM: DEBUG

# management endpoint
management:
  endpoint:
    metrics.enabled: true
  endpoints:
    web:
      exposure.include: '*'

# command
command:
  cache:
    configurations:
      getMemberCommandImpl: 60s
    enable: true
  interceptor:
    configurations:
      getMemberCommandImpl:
        - beanName: commandCacheInterceptor
          action: AFTER_SUCCESS

# rest
rest-log:
  enable: true
  masked:
    headers:
      - User-Agent
    payloads:
      - email
    responses:
      - email
  ignored-paths:
    GET:
      - /webjars/**
      - /actuator/**

# metrics
metrics:
  timer:
    slow-response-threshold: ${SLOW_RESPONSE_THRESHOLD:1000}