server:
  port: 8001
spring:
  application:
    name: core-app
  r2dbc:
#    url: r2dbc:postgresql://host.docker.internal:5432/local_db
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/local_db}
    username: 'user'
    password: 'password'
# logging
logging:
  level:
    com.nantaaditya.framework: DEBUG
    com.nantaaditya.framework.redis: DEBUG
    com.nantaaditya.framework.helper: INFO
  file:
    name: logs/core.log
#    io.r2dbc.postgresql.QUERY: DEBUG
#    io.r2dbc.postgresql.PARAM: DEBUG

# rest
rest-log:
  enable: true
  masked:
    payloads:
      - email
    responses:
      - email
  ignored-paths:
    GET:
      - /webjars/**
      - /actuator/**

# idempotent checker
audit.idempotent-check:
  configurations:
    TopUpRequest:
      idempotentFields:
        - $.memberId
        - $.referenceId
      checker: dbIdempotentChecker

# spring management
management:
  endpoint:
    metrics.enabled: true
  endpoints:
    web:
      exposure.include: '*'

# metrics module
metrics:
  timer:
    slow-response-threshold: ${SLOW_RESPONSE_THRESHOLD:1000}

# reactor schedulers
schedulers.configurations:
  changelog-schedulers:
    type: NEW_BOUNDED_ELASTIC
    new-bounded-elastic:
      name: changelog-schedulers